services:
  # 1. Baza danych
  db:
    image: postgres:15-alpine
    container_name: casino-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: casino_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d casino_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Backend API
  backend:
    build: ./backend
    image: casino-backend
    container_name: casino-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Tutaj u≈ºywamy nazwy serwisu 'db' zamiast 'localhost'
      DATABASE_URL: "postgresql://postgres:password123@db:5432/casino_db?schema=public"
      JWT_SECRET: "TwojeBardzoTajneHaslo123"
    depends_on:
      db:
          condition: service_healthy
    entrypoint: /app/entrypoint.sh

  # 3. Frontend React
  frontend:
    build: ./frontend
    container_name: casino-frontend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - backend

  # 4. Prisma Studio
  prisma-studio:
    build: ./backend
    container_name: casino-prisma-studio
    command: npx prisma studio --hostname 0.0.0.0
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://postgres:password123@db:5432/casino_db?schema=public"
    depends_on:
      - db

volumes:
  postgres_data: