version: '3.8'

services:
  # 1. Baza danych
  db:
    image: postgres:15-alpine
    container_name: casino-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: casino_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Backend API
  backend:
    build: ./backend
    image: casino-backend-v2
    container_name: casino-backend-v2
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Tutaj u≈ºywamy nazwy serwisu 'db' zamiast 'localhost'
      DATABASE_URL: "postgresql://postgres:password123@db:5432/casino_db?schema=public"
      JWT_SECRET: "TwojeBardzoTajneHaslo123"
    depends_on:
      - db

  # 3. Frontend React
  frontend:
    build: ./frontend
    container_name: casino-frontend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - backend

volumes:
  postgres_data: